yarnPath: .yarn/releases/yarn-4.0.2.cjs
enableGlobalCache: false
cacheFolder: .yarn/cache
patchFolder: .yarn/patches
nodeLinker: pnp
packageExtensions:
  '@toast-ui/editor@*':
    dependencies:
      prosemirror-transform: '*'
